# Generated by Django 4.1 on 2022-08-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arthicle',
            new_name='Article',
        ),
    ]
